version: "3"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env/production/database
      - .env/production/web
    depends_on:
      - redis
      - database
  redis:
    image: redis:alpine
  database:
    image: postgres:13-alpine
    env_file:
      - .env/production/database
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
